name: Django CI/CD

on:
  push:
    branches:
      - main  # o la rama que uses para producción

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"  # Puedes cambiar la versión

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Realizar migraciones
        run: |
          python manage.py migrate

      - name: Crear superusuario (solo si necesario)
        run: |
          echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(username='admin').exists() or User.objects.create_superuser('admin', 'admin@example.com', 'adminpass')" | python manage.py shell

      - name: Ejecutar pruebas
        run: |
          python manage.py test

      # OPCIONAL: Desplegar en un servidor remoto vía SSH
      # - name: Deploy to server
      #   uses: appleboy/ssh-action@v1.0.0
      #   with:
      #     host: ${{ secrets.SERVER_IP }}
      #     username: ${{ secrets.SERVER_USER }}
      #     key: ${{ secrets.SERVER_SSH_KEY }}
      #     script: |
      #       cd /ruta/a/tu/proyecto
      #       git pull origin main
      #       source venv/bin/activate
      #       pip install -r requirements.txt
      #       python manage.py migrate
      #       systemctl restart gunicorn

