name: Django CI/CD

on:
  push:
    branches:
      - main  # Ajusta si tu rama principal tiene otro nombre

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    env:
      CI: true  # Esta variable evita que pywhatkit se importe en entornos CI

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install django-crispy-forms
          pip install pillow
          pip install flask
          pip install pywhatkit
          pip install keyboard

      - name: Aplicar migraciones
        run: python manage.py migrate

      - name: Crear superusuario (si no existe)
        run: |
          echo "from django.contrib.auth import get_user_model; \
          User = get_user_model(); \
          User.objects.filter(username='admin').exists() or \
          User.objects.create_superuser('admin', 'admin@example.com', 'adminpass')" | python manage.py shell

      - name: Ejecutar tests
        run: python manage.py test

      # Puedes agregar aquí otros pasos como lint, cobertura o despliegue
